In [2]:
import pandas as pd
import json
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions
from bs4 import BeautifulSoup
import re
import pandas as pd
import numpy as np
from datetime import date, timedelta, datetime
import time
df=pd.read_csv("cities.csv")

In [3]:
df

   Code IMP_codes
0   AGR       DEL
1   DIB       BOM
2   HYD       BLR
3   BHJ       HYD
4   HBX       MAA
..  ...       ...
79  IXS       NaN
80  CNN       NaN
81  GOI       NaN
82  AMD       NaN
83  TIR       NaN

[84 rows x 2 columns]

In [4]:
df["IMP_codes"].iloc[29]

'TRZ'

In [11]:
from tqdm import tqdm
price=[]
cities=[]
departure_time=[]
arrival_time=[]
via=[]
airline=[]
cabin=[]
scraping_time = []
driver = webdriver.Chrome("C:\Program Files (x86)\chromedriver.exe")

for z in range(30, 32):
    driver.refresh()
    for m in range(29, 30):
        driver.refresh()
        for n in range(30):
            driver.refresh()
            if df["IMP_codes"].iloc[m]!=df["IMP_codes"].iloc[n]:
                print("source=",m, "destination=",n, "Dates=",z)
                print(df["IMP_codes"].iloc[m],df["IMP_codes"].iloc[n])
                k=''
                if(z<10):
                    k='0'
                url="https://www.makemytrip.com/flight/search?itinerary="+df["IMP_codes"].iloc[m]+"-"+df["IMP_codes"].iloc[n]+"-"+k+str(z)+"/05/2021&tripType=O&paxType=A-1_C-0_I-0&intl=false&cabinClass=PE&ccde=IN&lang=eng"
                #driver = webdriver.Chrome("C:/chromedriver.exe")
                driver.get(url)
                soup=BeautifulSoup(driver.page_source, 'lxml')

                price_info=soup.find_all('p',attrs={'class': 'blackText fontSize18 blackFont'})
                flights_info=soup.find_all('p',attrs={'class': 'flightDetailsHead'})
                time_info=soup.find_all('p',attrs={'class':"blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter"})
                layover_info=soup.find_all('p',attrs={'class': 'flightsLayoverInfo'})
                airline_info=soup.find_all('span',attrs={'class': 'boldFont blackText airlineName'})
                now1 = datetime.now()
                print("now =", now1)

#price_info
                for i,j in enumerate(price_info):
                    if i<30:
                       a=str(j)
                       price.append(a[43:len(a)-4])
                      
    #flights_info
                for i,j in enumerate(flights_info):
                    if i<60:
                        k=str(j)
                        if len(k)>45:
                            cities.append(k[29:(len(k)-4)])
                            scraping_time.append(now1)

    #time_info
                for i,j in enumerate(time_info):
                    if i<60:
                        k=str(j)
                        if (i%2==0):
                            departure_time.append(k[82:87])
                        if (i%2!=0):
                            arrival_time.append(k[82:87])

    #layover_info
                for i,j in enumerate(layover_info):
                    if i<30:
                        k=str(j)
                        via.append(k[30:len(k)-4])

    #airline_info
                for i,j in enumerate(airline_info):
                    if i<30:            
                        k=str(j)
                        airline.append(k[45:len(k)-7])
                print("**"*50)
                print(len(departure_time), len(price),len(cities),len(arrival_time),len(via),len(airline),len(scraping_time))

source= 29 destination= 0 Dates= 30
TRZ DEL
now = 2021-05-18 20:18:14.411469
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 1 Dates= 30
TRZ BOM
now = 2021-05-18 20:19:43.017739
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 2 Dates= 30
TRZ BLR
now = 2021-05-18 20:20:25.685412
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 3 Dates= 30
TRZ HYD
now = 2021-05-18 20:20:46.148452
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 4 Dates= 30
TRZ MAA
now = 2021-05-18 20:21:09.054329
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 5 Dates= 30
TRZ CCU
now = 2021-05-18 20:21:32.246129
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 6 Dates= 30
TRZ COK
now = 2021-05-18 20:21:51.306571
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 7 Dates= 30
TRZ GOI
now = 2021-05-18 20:22:14.023822
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 8 Dates= 30
TRZ PNQ
now = 2021-05-18 20:22:37.277139
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 9 Dates= 30
TRZ GAU
now = 2021-05-18 20:23:39.296314
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 10 Dates= 30
TRZ LKO
now = 2021-05-18 20:25:05.965262
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 11 Dates= 30
TRZ JAI
now = 2021-05-18 20:26:01.175189
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 12 Dates= 30
TRZ PAT
now = 2021-05-18 20:29:59.821980
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 13 Dates= 30
TRZ TRV
now = 2021-05-18 20:30:45.682135
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 14 Dates= 30
TRZ BBI
now = 2021-05-18 20:31:30.986096
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 15 Dates= 30
TRZ CCJ
now = 2021-05-18 20:32:16.278944
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 16 Dates= 30
TRZ IXB
now = 2021-05-18 20:32:40.468718
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 17 Dates= 30
TRZ NAG
now = 2021-05-18 20:33:24.307942
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 18 Dates= 30
TRZ VNS
now = 2021-05-18 20:34:09.743305
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 19 Dates= 30
TRZ IDR
now = 2021-05-18 20:34:27.048865
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 20 Dates= 30
TRZ CJB
now = 2021-05-18 20:34:48.120381
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 21 Dates= 30
TRZ SXR
now = 2021-05-18 20:35:10.872807
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 22 Dates= 30
TRZ VTZ
now = 2021-05-18 20:35:33.420031
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 23 Dates= 30
TRZ IXR
now = 2021-05-18 20:35:50.393649
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 24 Dates= 30
TRZ ATQ
now = 2021-05-18 20:36:13.299391
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 25 Dates= 30
TRZ IXC
now = 2021-05-18 20:36:38.445356
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 26 Dates= 30
TRZ RPR
now = 2021-05-18 20:37:01.339657
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 27 Dates= 30
TRZ IXE
now = 2021-05-18 20:37:24.136681
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 28 Dates= 30
TRZ IXZ
now = 2021-05-18 20:37:36.412021
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 0 Dates= 31
TRZ DEL
now = 2021-05-18 20:38:20.143574
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 1 Dates= 31
TRZ BOM
now = 2021-05-18 20:38:32.431930
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 2 Dates= 31
TRZ BLR
now = 2021-05-18 20:38:47.794503
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 3 Dates= 31
TRZ HYD
now = 2021-05-18 20:39:05.624403
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 4 Dates= 31
TRZ MAA
now = 2021-05-18 20:39:18.642851
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 5 Dates= 31
TRZ CCU
now = 2021-05-18 20:39:44.192275
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 6 Dates= 31
TRZ COK
now = 2021-05-18 20:40:05.221028
****************************************************************************************************
0 0 0 0 0 0 0
source= 29 destination= 7 Dates= 31
TRZ GOI

NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=90.0.4430.212)

In [7]:
data = pd.DataFrame(
    {'Price':price,
     'Cities':cities,
     'departure_time':departure_time,
     'arrival_time':arrival_time, 
     'layeover':via,
     'Airline':airline,
     'Scraping_Time':scraping_time
    })

In [8]:
data

,Price,Cities,departure_time,arrival_time,layeover,Airline,Scraping_Time
0,"4,850","Indore to New Delhi , 30 May",10:30,11:50,Non stop,Vistara,2021-05-18 17:09:22.350367
1,"5,910","Srinagar to New Delhi , 30 May",12:50,14:30,Non stop,Vistara,2021-05-18 17:41:04.236478
2,"5,176","Srinagar to New Delhi , 30 May",13:15,14:45,Non stop,Spicejet,2021-05-18 17:41:04.236478
3,"5,176","Srinagar to New Delhi , 30 May",08:50,10:30,Non stop,Spicejet,2021-05-18 17:41:04.236478
4,"5,176","Srinagar to New Delhi , 30 May",12:35,14:15,Non stop,Spicejet,2021-05-18 17:41:04.236478
...,...,...,...,...,...,...,...
69,"9,338","Port Blair to Mumbai , 30 May",09:50,23:50,1 stop via Chennai,Spicejet,2021-05-18 18:54:08.033309
70,"9,338","Port Blair to Mumbai , 30 May",09:50,08:20,1 stop via Chennai,Spicejet,2021-05-18 18:54:08.033309
71,"11,092","Port Blair to Bengaluru , 30 May",09:50,09:05,1 stop via Chennai,Spicejet,2021-05-18 18:54:26.448875
72,"5,588","Port Blair to Chennai , 30 May",09:50,12:05,Non stop,Spicejet,2021-05-18 18:54:55.075452
73,"5,313","Port Blair to Kolkata , 30 May",11:55,14:20,Non stop,Vistara,2021-05-18 18:54:58.842242

In [9]:
print(len(departure_time), len(price),len(cities),len(arrival_time),len(via),len(airline), len(scraping_time))

74 74 74 74 74 74 74

In [10]:
data.to_csv("new_pe_may30_5th.csv", index = False)

In [201]:
df.tail()

   Code IMP_codes
79  IXS       NaN
80  CNN       NaN
81  GOI       NaN
82  AMD       NaN
83  TIR       NaN